//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonMua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonMua()
        {
            this.ChiTietMuas = new HashSet<ChiTietMua>();
        }
    
        public int MaHDM { get; set; }
        public string MaHang { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayMua { get; set; }
        public decimal TongTien { get; set; }
        public decimal TienNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietMua> ChiTietMuas { get; set; }
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
