//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietBans = new HashSet<ChiTietBan>();
            this.ChiTietMuas = new HashSet<ChiTietMua>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string HinhAnh { get; set; }
        public decimal DonGia { get; set; }
        public string MoTa { get; set; }
        public int SoLuong { get; set; }
        public string ManHinh { get; set; }
        public string HDH { get; set; }
        public string CameraTruoc { get; set; }
        public string CameraSau { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string BoNhoTrong { get; set; }
        public string TheNho { get; set; }
        public string TheSIM { get; set; }
        public string DungLuongPin { get; set; }
        public string MaHang { get; set; }
        public string MaLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBan> ChiTietBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietMua> ChiTietMuas { get; set; }
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
